### ISSUE TITLE
Lab Report Feedback 2

### ISSUE THREAD

**Issue by daniel-n-ryu** [natalieycyoung/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
  - What markdown file did you provide as input?
- [x] Symptom shown as command + output for bug/input 1
  - No symptom, command, or output provided for the bug
- [x] Description of relationship between bug, symptom, and input for bug/input 1
  - What was the bug? What was the cause? Why did it fail on the provided input?

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
If there is any confusion on the assignment, feel free to leave questions on this issue or visit office hours

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by daniel-n-ryu** [comment]
Many of the missing pieces for this assignment are still missing, especially for bugs 2 and 3. What is bug 1, and how did you fix it? Need a paragraph description of this

**Comment by natalieycyoung** [comment]
Hi, thanks for the feedback. I wasn't able to complete those parts sooner, but they're fixed now.
