### ISSUE TITLE
Lab Report 3 Feedback

### ISSUE THREAD

**Issue by yahmad3495** [natalieycyoung/cse15l-lab-reports#3]
Here is your feedback for Lab Report 3 - Streamlining `ssh` Configuration:

- [x] Show your `.ssh/config` file, and how you edited it (with VScode, another program, etc)
- [x] Show the `ssh` command logging you into your account using just the alias you chose.
- [x] Show an `scp` command copying a file to your account using just the alias you chose.
     -Please include a screenshot of using the scp command with your alias created

Additional comments from your grader:
Great work! Feel free to leave any questions below!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by natalieycyoung** [comment]
Hi Younus,

Thank you for your feedback.

The lab report instructions (pictured below) said to do a writeup for only one of the group options from the Week 5 lab, which I've done.

![image](https://user-images.githubusercontent.com/44858512/155459129-8c4e02b0-b595-492d-9678-565c07472c98.png)

That being said, I've added another section for the `scp` command option.

**Comment by yahmad3495** [comment]
Hi Natalie, I think we just wanted to use the alias you created with scp to show that the alias will work for both commands. Thanks for including it!
